### ISSUE TITLE
autoreverse questions

### ISSUE THREAD

**Issue by Rico29** [cmouse/pdns-v6-autorev#7]
Hello,

I'm trying to make autoreverse work.

here's my pdns config : 
launch=remote,gmysql
remote-connection-string=pipe:command=/usr/local/src/pdns-v6-autorev/rev.pl,timeout=2000,dsn=DBI:mysql:pdns,username=pdns,password=pdns
remote-dnssec=no # depending on your choice

In my mysql DB, I have : 

mysql> select * from domains;
+----+--------------------+--------+------------+--------+-----------------+---------+
| id | name               | master | last_check | type   | notified_serial | account |
+----+--------------------+--------+------------+--------+-----------------+---------+
|  1 | zone-dev.fr       | NULL   |       NULL | MASTER |            NULL | NULL    |
|  2 | 3.2.1.in-addr.arpa | NULL   |       NULL | MASTER |            NULL | NULL    |
+----+--------------------+--------+------------+--------+-----------------+---------+

mysql> select * from domainmetadata;
+----+-----------+---------+---------+
| id | domain_id | kind    | content |
+----+-----------+---------+---------+
|  2 |         2 | AUTODNS | 1       |
+----+-----------+---------+---------+

mysql> select * from records where type='A';
+----+-----------+-------------------+------+---------+-------+------+-------------+----------+-----------+------+
| id | domain_id | name              | type | content | ttl   | prio | change_date | disabled | ordername | auth |
+----+-----------+-------------------+------+---------+-------+------+-------------+----------+-----------+------+
|  6 |         1 | test.zone-dev.fr | A    | 1.2.3.4 | 86400 |    0 |  1457365376 |        0 | NULL      |    1 |
+----+-----------+-------------------+------+---------+-------+------+-------------+----------+-----------+------+

testing : 
[root@ipv6 pdns-v6-autorev]# dig test.zone-dev.fr @localhost +short
1.2.3.4
[root@ipv6 pdns-v6-autorev]# dig -x 1.2.3.4 @localhost +short
-> returns nothing
[root@ipv6 pdns-v6-autorev]# dig PTR 4.3.2.1.in-addr.arpa @127.0.0.1 +short
-> returns nothing

Can you help me with that please ?

regards

PS : I have warnings in pdns logfile : 
Use of implicit split to @_ is deprecated at /usr/local/src/pdns-v6-autorev/rev.pl line 650.

**Comment by cmouse** [comment]
On Mon, Mar 07, 2016 at 08:04:12AM -0800, Rico29 wrote:
> Hello,
> 
> I'm trying to make autoreverse work.
> 
> here's my pdns config : 
> launch=remote,gmysql
> remote-connection-string=pipe:command=/usr/local/src/pdns-v6-autorev/rev.pl,timeout=2000,dsn=DBI:mysql:pdns,username=pdns,password=pdns
> remote-dnssec=no # depending on your choice
> 

As the name implies, it is for IPv6. Not IPv4.

Aki

**Comment by Rico29** [comment]
Hello Aki,

Now, my questions seems stupid :)

Thanks.

**Comment by Rico29** [comment]
I'm still having the 
"Use of implicit split to @_ is deprecated at /usr/local/src/pdns-v6-autorev/rev.pl line 650."
warning each time I make a request.
l. 650 :   my $qnibbles = scalar(split(/ /, $p->{qname}));
Any idea on the way to fix this ? I'm not good enough to fix that myself. Tried different things but none of them worked.

Regards

**Comment by cmouse** [comment]
hmm, you can remove use warnings for now, I'll see if I can fix that soon. can you provide your perl version?

**Comment by Rico29** [comment]
OK
I'm using perl 5.10.1

**Comment by cmouse** [comment]
thanks. sorry for late response.
