### ISSUE TITLE
Mandatory trailing dot in pdns-4.x.x breaks plugin

### ISSUE THREAD

**Issue by James-TR** [cmouse/pdns-v6-autorev#8]
PowerDNS 4.x.x now adds a mandatory trailing "." to the end of every qname. I'm not sure when this first started, but I've had to make a slight adjustment to fix the database queries being performed for zone matching.

**Comment by cmouse** [comment]
Yeah we decided that it's the best option. Have to update this plugin to respect this.

**Comment by James-TR** [comment]
I made a dodgy diff which is working in the wild currently.
```
diff --git a/rev.pl b/rev.pl
index addb471..2c6dc17 100755
--- a/rev.pl
+++ b/rev.pl
@@ -317,6 +317,7 @@ sub do_lookup {
   my $self = shift;
   my $p = shift;
   my $name = $p->{qname};
+  $name =~ s/\.$//;
   my $type = $p->{qtype};
   my $d = $self->d;
   my $stmt;
```

**Comment by cmouse** [comment]
hm, could you possibly make this a pull request?
