### ISSUE TITLE
JSON::Any vs JSON::MaybeXS

### ISSUE THREAD

**Issue by James-TR** [cmouse/pdns-v6-autorev#9]
I have noticed that JSON::Any has been marked as "deprecated", and as such is eventually slated for removal (This is at least the case for Gentoo, not sure how other Distributions will handle this)

Where possible, JSON::MaybeXS can be used as a direct drop-in replacement ... I have tested this myself and haven't noticed any difference in behaviour.

**Comment by cmouse** [comment]
Have to check it's availability in other distros. Thanks for the headsup.

**Comment by cmouse** [comment]
Wonder how to handle the lack of JSON::MaybeXS...
